### ISSUE TITLE
remote_debugger.py: sys.gettrace() resets after exception.

### ISSUE THREAD

**Issue by Dykam** [sybrenstuvel/random-blender-addons#1]
This addon is amazing, however something odd happens, [somebody else](https://code.blender.org/2015/10/debugging-python-code-with-pycharm/#comment-63100) noticed as well.

Breakpoints work fine, until an exception happens. From that moment on, it only stops on exceptions and no longer on breakpoints. After some debugging, the output of `sys.gettrace()` changes from a bound function to simple `None`.

Value before: `<bound method ThreadTracer.__call__ of <_pydevd_bundle.pydevd_trace_dispatch_regular.ThreadTracer object at 0x000002562C60BDA0>>`.

The workaround at the bottom of https://stackoverflow.com/a/9502960/84535 works. The other workaround is to call the operator again (Pycharm for me). Any idea of a more persistent fix?

**Comment by sybrenstuvel** [comment]
As you can see from my late response I don't use this addon that much myself ;-)
I wouldn't know a proper solution by heart. If anyone wants to send a pull request I'd be happy to merge, but I don't have the time to investigate this myself.
