### ISSUE TITLE
Blender closes/crashes after resuming process from PyCharm

### ISSUE THREAD

**Issue by HG3D** [sybrenstuvel/random-blender-addons#12]
I was glad to find this add-on, since I would love to switch from VS Code to Pycharm in order to use the more robust debugging tools. However, I've run into a problem of which I'm not sure if it's caused by either Pycharm, this add-on or Blender itself.

# Summary:
Remote debugger successfully connects, but  **resuming** the instance from PyCharm - after an exception occured - causes  Blender to close/crash.

# Context:

- Blender version: 3.1.0
- OS: Both macOS Monterey and Windows 10

# Steps to reproduce:
1) Follow instructions to install add-on, point to debug egg and add debug configuration in Pycharm
1.5) Pip install `pydevd-pycharm~=221.5080.212`
2) Start the debug instance in Pycharm
3) Open Blender
4) Run the "Connect to Pycharm debugger" operator
> Now things work as expected, the console is being redirected to Pycharm
5) Do something that causes an exception in Blender
> Now Blender freezes, as expected, and Pycharm shows the exception in the debug window
6) Press "Resume" in the Pycharm debug window
> Blender closes/crashes, no crash log can be found. Last lines of console say:
> ```
> python-BaseException
> Waiting for process connection…
> ```

One other thing I should mention is the add-on says to find `pycharm-debug-py3k.egg`, while in the Pycharm files only `pycharm-debug.egg` is present. I'm assuming this is due to Python 2 no longer being supported, so the `py3k` suffix was removed, but I could be wrong about this.

---

Please let me know if there is any further information I can provide or things I can test to hopefully resolve the issue

**Comment by sybrenstuvel** [comment]
I'm not developing this add-on any more, haven't used it myself for years. I'll close this issue.
