### ISSUE TITLE
[Request] Remote Debugger Add-On is installable through Blender Editor from the Community Add-Ons menu

### ISSUE THREAD

**Issue by sf-aallbright** [sybrenstuvel/random-blender-addons#13]
First off: Thank you for creating this add-on!

I was curious about debugging python based blender scripts and found [this helpful blog on code.blender.org](https://code.blender.org/2015/10/debugging-python-code-with-pycharm/). It describes the process of using the remote debugger add-on maintained here. The instructions say to download and install the script into blender to get debugging working.

This is a request to be able to install the debug add-on through blender. It appears that blender does have a process for submitting an add-on ([docs](https://wiki.blender.org/wiki/Process/Addons)). Feel free to close this issue if this idea is not exciting, or really for whatever reason you decide not to pursue this. Thank you again for developing this add-on as it is very nice to debug scripts in pycharm IDE.

Cheers and thanks one last time!

**Comment by sybrenstuvel** [comment]
It's a nice idea, but then I'd have to maintain the add-on ;-)
