### ISSUE TITLE
Feature request Any chance we can get that timer bar to have an option to be permanently there in the viewport?

### ISSUE THREAD

**Issue by The-Maize** [sybrenstuvel/random-blender-addons#15]
That red timer bar that pops up after a while would be great to have that avaible at all times. even if it is togglable option for those that dont want it on at all times.

**Comment by sybrenstuvel** [comment]
Assuming you're talking about You Are Autosave: you'll get the bar permanently in there when you set the "Nag Start Time" to 0.

**Comment by The-Maize** [comment]
Thank you! thats great didn't realise that, i love that plugin, makes me laugh every time i come back to a blocked screen lmao. great job mate. best wanted troll ever.
