### ISSUE TITLE
Doesn't Show in List

### ISSUE THREAD

**Issue by smeben** [sybrenstuvel/random-blender-addons#5]
The addon isn't showing in the list after installing

**Comment by sybrenstuvel** [comment]
There are multiple addons in this repository. Which one did you download, and how did you install it?

**Comment by smeben** [comment]
Ah yes, it's the remote debugger

**Comment by sybrenstuvel** [comment]
Ok, so that is one of my two questions answered. And a third: have you enabled Python Tooltips and Developer Extras in Blender's preferences?

**Comment by smeben** [comment]
they were not. i have enabled them now, but it still isnt showing up in the addon list

**Comment by sybrenstuvel** [comment]
Ok, that's two questions down. You still haven't answered one. I'm not asking these questions for the fun of it, it's necessary to help you further.

**Comment by smeben** [comment]
oh i missed the how did i install, sorry. in the addons menu i click install and selected the downloaded py file

**Comment by sybrenstuvel** [comment]
Ah, in that case you've likely missed the link in the comments at the top of the Python file: 

For more information on how to use this addon, please read my article at
http://code.blender.org/2015/10/debugging-python-code-with-pycharm/

**Comment by smeben** [comment]
I'm not sure what you mean. I did read that page, and it says to use the install button and select the downloaded py file, which I did. But the addon then does not show up in the list...
Can you be more specific on what you think I missed in that article? Step one is what is not working for me.
FYI I am using Blender 2.82

**Comment by sybrenstuvel** [comment]
Have you checked the console for any error messages?

**Comment by smeben** [comment]
Yes, when I install it from the addons menu I get the following in the console
Modules Installed () from 'C:\\Users\\VACC001\\Downloads\\remote_debugger.py' into 'C:\\Users\\VACC001\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons'
